version: '3'
services:
    web:
      build: ./
      command: python -u app.py
      ports:
        - "5000:5000"
      volumes:
        - .:/pythonApp
      environment:
            MONGO_HOST: 127.0.0.1:27017
      links:
        - db
    db:
      image: mongo:4.0
      restart: always
      expose:
            - 27017
      ports:
        - "27017:27017"
      command: mongod --smallfiles